### ISSUE TITLE
faster package installation

### ISSUE THREAD

**Issue by donvipre** [while-true-do/ansible-role-yum#5]
### Type of Report

enhancement

### Actual behaviour

currently each yum requirement is installed as a seperate run in task "Install yum packages" which is very slow

### Expected behaviour

don't use with_items anymore there and replace item with the array wtd_yum_packages

**Comment by daniel-schier** [comment]
@donvipre Do you know the actual ansible-version which is needed for this? =)

**Comment by donvipre** [comment]
@daniel-wtd: with regards to: http://docs.ansible.com/ansible/latest/yum_module.html
in the attributes table on attribute name: "To operate on several packages this can accept a comma separated list of packages or (as of 2.0) a list of packages."

I think it should be possible since ansible 2.0

**Comment by daniel-schier** [comment]
@donvipre Same can be said about packages modules. Got the infomation from IRC.

So we can arrange the same change everywhere, when touching the roles.

It seems not critical, because we can also use some config to achieve the same:

ansible.cfg | .ansible.cfg
```
[defaults]
squash_actions = apk,apt,dnf,homebrew,package,pacman,pkgng,yum,zypper
```
